services:
    Akeneo\Connectivity\Connection\Infrastructure\Connections\WrongCredentialsCombination\EventSubscriber\ApiAuthenticationEventSubscriber:
        arguments:
            - '@akeneo_connectivity.connection.service.connection_context'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Connections\WrongCredentialsCombination\Persistence\DbalWrongCredentialsCombinationRepository'
        tags:
            - { name: kernel.event_subscriber }

    Akeneo\Connectivity\Connection\Infrastructure\Connections\WrongCredentialsCombination\EventSubscriber\ConnectionContextEventSubscriber:
        arguments:
            - '@akeneo_connectivity.connection.service.connection_context'
        tags:
            - { name: kernel.event_subscriber }
