services:
    Akeneo\Platform\Job\Application\FindJobType\FindJobTypeInterface:
        class: Akeneo\Platform\Job\Infrastructure\Query\FindJobType
        arguments:
            - '@database_connection'

    Akeneo\Platform\Job\Application\SearchJobUser\SearchJobUserInterface:
        class: Akeneo\Platform\Job\Infrastructure\Query\SearchJobUser
        arguments:
            - '@database_connection'

    Akeneo\Platform\Job\Application\SearchJobExecution\SearchJobExecutionInterface:
        class: Akeneo\Platform\Job\Infrastructure\Query\SearchJobExecution
        arguments:
            - '@database_connection'
            - '@Akeneo\Platform\Job\Infrastructure\Hydrator\JobExecutionRowHydrator'

    akeneo.job.query.get_job_instance_remote_storage:
        class: Akeneo\Platform\Job\Infrastructure\Query\JobInstanceRemoteStorage\GetJobInstanceRemoteStorage
        arguments:
            - '@database_connection'

    akeneo.job.query.save_job_instance_remote_storage:
        class: Akeneo\Platform\Job\Infrastructure\Query\JobInstanceRemoteStorage\SaveJobInstanceRemoteStorage
        arguments:
            - '@database_connection'
