# Product
pim_enrich_product_categories_view:
    type: action
    label: pim_enrich.acl.product.categories_view
    group_name: pim_enrich.acl_group.product
# Product Model
pim_enrich_product_model_categories_view:
    type: action
    label: pim_enrich.acl.product_model.categories_view
    group_name: pim_enrich.acl_group.product_model

# ProductCategory
pim_enrich_product_category_list:
    type: action
    label: pim_enrich.acl.category.list
    group_name: pim_enrich.acl_group.category
pim_enrich_product_category_create:
    type: action
    label: pim_enrich.acl.category.create
    group_name: pim_enrich.acl_group.category
pim_enrich_product_category_edit:
    type: action
    label: pim_enrich.acl.category.edit
    group_name: pim_enrich.acl_group.category
pim_enrich_product_category_remove:
    type: action
    label: pim_enrich.acl.category.remove
    group_name: pim_enrich.acl_group.category
pim_enrich_product_category_history:
    type: action
    label: pim_enrich.acl.category.history
    group_name: pim_enrich.acl_group.category
