services:
    akeneo_category.job.job_parameters.constraint_collection_provider.simple_csv_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleCsvExport'
        arguments:
            -
                - 'csv_category_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    akeneo_category.job.job_parameters.constraint_collection_provider.simple_xlsx_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxExport'
        arguments:
            -
                - 'xlsx_category_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    akeneo_category.job.job_parameters.constraint_collection_provider.simple_csv_import:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleCsvImport'
        arguments:
            -
                - 'csv_category_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    akeneo_category.job.job_parameters.constraint_collection_provider.simple_xlsx_import:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxImport'
        arguments:
            -
                - 'xlsx_category_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
