services:
    akeneo_category.job.job_parameters.default_values_provider.simple_csv_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleCsvExport'
        arguments:
            -
                - 'csv_category_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    akeneo_category.job.job_parameters.default_values_provider.simple_xlsx_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleXlsxExport'
        arguments:
            -
                - 'xlsx_category_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    akeneo_category.job.job_parameters.default_values_provider.simple_csv_import:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleCsvImport'
        arguments:
            -
                - 'csv_category_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    akeneo_category.job.job_parameters.default_values_provider.simple_xlsx_import:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleXlsxImport'
        arguments:
            -
                - 'xlsx_category_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
