services:
    akeneo.pim.enrichment.controller.product_grid_category_tree:
        class: 'Akeneo\Category\Infrastructure\Controller\InternalApi\ProductGridCategoryTreeController'
        public: true
        arguments:
            - '@akeneo.pim.enrichment.category.category_tree.list_root_categories_with_count_handler'
            - '@akeneo.pim.enrichment.category.category_tree.list_children_categories_with_count_handler'
            - '@akeneo.pim.enrichment.category.category_tree.normalizer.root_category'
            - '@akeneo.pim.enrichment.category.category_tree.normalizer.child_category'
            - '@pim_user.context.user'
            - '@oro_security.security_facade'

    akeneo.pim.enrichment.category.category_tree.list_root_categories_with_count_handler:
        class: 'Akeneo\Category\Infrastructure\Component\CategoryTree\UseCase\ListRootCategoriesWithCountHandler'
        arguments:
            - '@pim_catalog.repository.category'
            - '@pim_user.context.user'
            - '@akeneo.pim.enrichment.category.category_tree.query.list_root_categories_with_count_including_sub_categories'
            - '@akeneo.pim.enrichment.category.category_tree.query.list_root_categories_with_count_not_including_sub_categories'

    akeneo.pim.enrichment.category.category_tree.list_children_categories_with_count_handler:
        class: 'Akeneo\Category\Infrastructure\Component\CategoryTree\UseCase\ListChildrenCategoriesWithCountHandler'
        arguments:
            - '@pim_catalog.repository.category'
            - '@pim_user.context.user'
            - '@akeneo.pim.enrichment.category.category_tree.query.list_children_categories_with_count_including_sub_categories'
            - '@akeneo.pim.enrichment.category.category_tree.query.list_children_categories_with_count_not_including_sub_categories'

    akeneo.pim.enrichment.category.category_tree.query.list_root_categories_with_count_including_sub_categories:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\CategoryTree\ListRootCategoriesWithCountIncludingSubCategories'
        arguments:
            - '@database_connection'
            - '@akeneo_elasticsearch.client.product_and_product_model'

    akeneo.pim.enrichment.category.category_tree.query.list_root_categories_with_count_not_including_sub_categories:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\CategoryTree\ListRootCategoriesWithCountNotIncludingSubCategories'
        arguments:
            - '@database_connection'
            - '@akeneo_elasticsearch.client.product_and_product_model'

    akeneo.pim.enrichment.category.category_tree.query.list_children_categories_with_count_including_sub_categories:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\CategoryTree\ListChildrenCategoriesWithCountIncludingSubCategories'
        arguments:
            - '@database_connection'
            - '@akeneo_elasticsearch.client.product_and_product_model'

    akeneo.pim.enrichment.category.category_tree.query.list_children_categories_with_count_not_including_sub_categories:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\CategoryTree\ListChildrenCategoriesWithCountNotIncludingSubCategories'
        arguments:
            - '@database_connection'
            - '@akeneo_elasticsearch.client.product_and_product_model'

    akeneo.pim.enrichment.category.category_tree.normalizer.root_category:
        class: 'Akeneo\Category\Infrastructure\Component\CategoryTree\Normalizer\RootCategory'

    akeneo.pim.enrichment.category.category_tree.normalizer.child_category:
        class: 'Akeneo\Category\Infrastructure\Component\CategoryTree\Normalizer\ChildCategory'
