services:
    pim_catalog.remover.category:
        class: '%pim_catalog.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pim_catalog.entity.category.class%'
