parameters:
    pim_catalog.repository.product_category.class:      Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\ProductCategoryRepository
    pim_catalog.repository.product_model_category.class: Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\ProductModelCategoryRepository

services:
    pim_catalog.repository.category:
        class: 'Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\CategoryRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['%pim_catalog.entity.category.class%']
        tags:
            - { name: 'category_repository' }

    pim_catalog.repository.cached_category:
        class: '%akeneo_storage_utils.repository.base_cached_object.class%'
        arguments:
            - '@pim_catalog.repository.category'

    pim_catalog.repository.product_category:
        class:  '%pim_catalog.repository.product_category.class%'
        parent: akeneo_classification.repository.abstract_item_category
        arguments:
            - '@pim_catalog.object_manager.product'
            - '%pim_catalog.entity.product.class%'
            - '%pim_catalog.entity.category.class%'

    pim_catalog.repository.product_model_category:
        class:  '%pim_catalog.repository.product_model_category.class%'
        parent: akeneo_classification.repository.abstract_item_category
        arguments:
            - '@pim_catalog.object_manager.product'
            - '%pim_catalog.entity.product_model.class%'
            - '%pim_catalog.entity.category.class%'

    pim_api.repository.category:
        class: 'Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\ExternalApi\CategoryRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'
            - '@pim_catalog.repository.category'

    pim_enrich.repository.category:
        public: true
        class: 'Akeneo\Category\Infrastructure\Doctrine\ORM\Repository\InternalApi\CategoryRepository'
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'
