services:
    pim_connector.step.csv_category.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.csv_category'
            - '@pim_connector.processor.denormalization.category'
            - '@pim_connector.writer.database.category'
            - 1
            - '@akeneo_batch.job.job_stopper'

    pim_connector.step.csv_category.export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.category'
            - '@pim_connector.processor.normalization.category'
            - '@pim_connector.writer.file.csv_category'
            - 100
            - '@akeneo_batch.job.job_stopper'

    pim_connector.step.xlsx_category.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.xlsx_category'
            - '@pim_connector.processor.denormalization.category'
            - '@pim_connector.writer.database.category'
            - 1
            - '@akeneo_batch.job.job_stopper'

    pim_connector.step.xlsx_category.export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.category'
            - '@pim_connector.processor.normalization.category'
            - '@pim_connector.writer.file.xlsx_category'
            - 10
            - '@akeneo_batch.job.job_stopper'
