services:
    pim_enrich.twig.category_extension:
        class: 'Akeneo\Category\Infrastructure\Twig\CategoryExtension'
        arguments:
            - '@pim_enrich.doctrine.counter.category_registry'
            - '%max_products_category_removal%'
        tags:
            - { name: twig.extension }
