parameters:
    pim_catalog.updater.setter.category_field.class:          Akeneo\Category\Infrastructure\Component\Product\Updater\Setter\CategoryFieldSetter
    pim_catalog.updater.adder.category_field.class:           Akeneo\Category\Infrastructure\Component\Product\Updater\Adder\CategoryFieldAdder
    pim_catalog.updater.remover.category_field.class:         Akeneo\Category\Infrastructure\Component\Product\Updater\Remover\CategoryFieldRemover
    pim_catalog.updater.category_translatable.class:          Akeneo\Category\Infrastructure\Component\CategoryUpdater

services:

    akeneo_category.updater.translatable:
        class: 'Akeneo\Tool\Component\Localization\TranslatableUpdater'

    # Updaters
    pim_catalog.updater.category:
        class: '%akeneo_classification.updater.category.class%'
        arguments:
            - '@pim_catalog.repository.category'
            - '@pim_user.query.is_category_tree_linked_to_user'
            - '@pim_channel.query.sql.is_category_tree_linked_to_channel'

    pim_catalog.updater.category_translatable:
        decorates: pim_catalog.updater.category
        decoration_inner_name: pim_catalog.updater.category.base
        class: '%pim_catalog.updater.category_translatable.class%'
        arguments:
            - '@pim_catalog.updater.category.base'
            - '@akeneo_category.updater.translatable'

    # Setters
    pim_catalog.updater.setter.category_field:
        class: '%pim_catalog.updater.setter.category_field.class%'
        arguments:
            - '@pim_catalog.repository.cached_category'
            - ['categories']
        tags:
            - { name: 'pim_catalog.updater.setter' }

    # Adders
    pim_catalog.updater.adder.category_field:
        class: '%pim_catalog.updater.adder.category_field.class%'
        arguments:
            - '@pim_catalog.repository.cached_category'
            - ['categories']
        tags:
            - { name: 'pim_catalog.updater.adder' }

    # Removers
    pim_catalog.updater.remover.category_field:
        class: '%pim_catalog.updater.remover.category_field.class%'
        arguments:
            - '@pim_catalog.repository.cached_category'
            - ['categories']
        tags:
            - { name: 'pim_catalog.updater.remover' }

    # Clearers
    pim_catalog.updater.clearer.category_field:
        class: 'Akeneo\Category\Infrastructure\Component\Product\Updater\Clearer\CategoryFieldClearer'
        tags:
            - { name: 'pim_catalog.updater.clearer' }
