services:
    akeneo.pim.enrichment.controller.product_grid_filter:
        class: 'Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\ProductGridFilterController'
        public: true
        arguments:
            - '@oro_datagrid.datagrid.manager'
            - '@security.token_storage'
            - '@pim_enrich.repository.attribute.search'
            - '@pim_enrich.normalizer.attribute'
            - '@pim_user.context.user'
            - '@translator.default'
